#docker-compose.yml (Base)
version: "3.7"
networks:
  sample:
    name: sample-network
    driver: bridge
services:
  api-dev:
    image: "openjdk:14-alpine"
    container_name: api-dev
    volumes:
      - ./build/libs:/usr/src/myapp
    working_dir: /usr/src/myapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command:
      [
        "java",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/usr/src/myapp/service.jar",
      ]
    networks:
      - sample
    expose:
      - "5000"
    ports:
      - 5000:5000
