#docker-compose.yml (Base)
version: "3.7"
networks:
  sample:
    name: sample-network
    driver: bridge
volumes:
  sonar-postgres:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
services:
  sonar-fe:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-fe
    volumes:
      - ./fe/:/usr/src/myapp
    working_dir: /usr/src/myapp
    networks:
      - sample
    depends_on:
      - sonarqube-sample
    command: sonar-scanner  -Dsonar.login=7fdb399cd4e4c39d549f14fd7634524fe026bf8e -Dsonar.projectKey=sample-fe -Dsonar.sources=. -Dsonar.exclusions=e2e_tests/reports/** -Dsonar.host.url=http://sonarqube-sample:9000   -Dsonar.scm.disabled=True
  sonar-api:
    image: openjdk:13.0.2-slim
    container_name: sonar-api
    volumes:
      - ./api/:/usr/src/myapp
    working_dir: /usr/src/myapp
    networks:
      - sample
    depends_on:
      - sonarqube-sample
    command: ./gradlew sonarqube -x test -Dsonar.login=2cae8034a9a8d1fc5476409b7da18d386988ee7c -Dsonar.projectKey=sample-api -Dsonar.host.url=http://sonarqube-sample:9000   -Dsonar.scm.disabled=True
  sonarqube-sample:
    image: sonarqube:8.3-community
    container_name: sonarqube-sample
    ports:
      - 9001:9000
    networks:
      - sample
    environment:
      - sonar.jdbc.username=dev
      - sonar.jdbc.password=dev123
      - sonar.jdbc.url=jdbc:postgresql://sonar-postgres/sonar
      - sonar.search.javaAdditionalOpts=-Dbootstrap.system_call_filter=false
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - sonar-postgres
  sonar-postgres:
    image: postgres:12
    container_name: sonar-postgres
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=dev
      - POSTGRES_DB=sonar
    volumes:
      - sonar-postgres:/var/lib/postgresql/data:z
    ports:
      - "5445:5432"
    networks:
      - sample
