#docker-compose.yml (Base)
version: "3.8"
networks:
  sample:
    name: sample-network
    driver: bridge
volumes:
  api-postgres:
    external: true
  redisinsight-sample:
  redis-sample:
services:
  vault-sample:
    image: vault:latest
    container_name: vault-sample
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=sample
    networks:
      - sample
  rabbitmq-sample:
    image: "bitnami/rabbitmq:latest"
    container_name: rabbitmq-sample
    environment:
      - RABBITMQ_USERNAME=dev
      - RABBITMQ_PASSWORD=dev123
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - sample
  api-postgres:
    image: library/postgres:14
    container_name: api-postgres
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=dev
      - POSTGRES_DB=sample
    volumes:
      - api-postgres:/var/lib/postgresql/data:z
    ports:
      - "5444:5432"
    networks:
      - sample
  keycloak-sample:
    image: jboss/keycloak:16.1.0
    container_name: keycloak-sample
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_SCHEMA=keycloak
      - DB_DATABASE=sample
      - DB_ADDR=api-postgres
      - DB_USER=dev
      - DB_PASSWORD=dev123
      - JDBC_PARAMS=useSSL=false
      - "JAVA_OPTS=-Djboss.socket.binding.port-offset=-1900"
    ports:
      - "6180:6180"
    depends_on:
      - api-postgres
    networks:
      - sample
    # healthcheck:
    #   test: "curl -f http://localhost:8080/auth || exit 1"
    #   start_period: 20s
  redis-sample:
    image: redis:6.2.6-alpine
    container_name: redis-sample
    networks:
      - sample
    volumes:
      - redis-sample:/data:z
    ports:
      - "6378:6379"
  redis-insight:
    container_name: redis-insight-sample
    image: redislabs/redisinsight:1.11.0
    ports:
      - "8002:8001"
    volumes:
      - redisinsight-sample:/db
    networks:
      - sample
    depends_on:
      - redis-sample