#docker-compose.yml (Base)
#https://github.com/wrouesnel/postgres_exporter
version: "3.7"
networks:
  sample:
    name: sample-network
    driver: bridge
volumes:
  api-postgres:
    external: true
  redisinsight-sample:
  redis-sample:
services:
  api-postgres:
    image: library/postgres:14
    container_name: api-postgres
    environment:
      - POSTGRES_PASSWORD=dev123
      - POSTGRES_USER=dev
      - POSTGRES_DB=sample
    volumes:
      - api-postgres:/var/lib/postgresql/data:z
    ports:
      - "5444:5432"
    networks:
      - sample
  keycloak-sample:
    image: jboss/keycloak:12.0.1
    container_name: keycloak-sample
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_SCHEMA=keycloak
      - DB_DATABASE=sample
      - DB_ADDR=api-postgres
      - DB_USER=dev
      - DB_PASSWORD=dev123
      - JDBC_PARAMS=useSSL=false
      - "JAVA_OPTS=-Djboss.socket.binding.port-offset=-1900"
    ports:
      - "6180:6180"
    depends_on:
      - api-postgres
    networks:
      - sample
    # healthcheck:
    #   test: "curl -f http://localhost:8080/auth || exit 1"
    #   start_period: 20s
  redis-sample:
    image: redis:6.0.0-alpine
    container_name: redis-sample
    networks:
      - sample
    volumes:
      - redis-sample:/data:z
    ports:
      - "6378:6379"
  redis-insight:
    container_name: redis-insight-sample
    image: redislabs/redisinsight:latest
    ports:
      - "8002:8001"
    volumes:
      - redisinsight-sample:/db
    networks:
      - sample
    depends_on:
      - redis-sample
