#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

apps=(api)
for app in "${apps[@]}"
do
a="${REPO_ROOT_DIR}/${app}"
cd "$a"
    echo "----Start formating $a ----"
    sh "gradlew" format  
	echo $PWD
	cd $OLDPWD
	echo $PWD
done 
git add . 