#!/bin/sh

set -e

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

apps=(api)
for app in "${apps[@]}"
do
a="${REPO_ROOT_DIR}/${app}"
if [ -d "$a" ] 
then
   cd "$a"
    echo "----Start formating $a ----"
    sh "gradlew" format  
else
    echo "Error: Directory $a does not exists."
fi

done 
git add . 