sample:
    internal-api: http://localhost:5001/
server:
    port: 5000
info:
    app:
        description: playground application
        name: Spring Backyard API Gateway Application
    java-vendor: ${java.specification.vendor}
logging:
    level:
        root: DEBUG
spring:
    cache:
        type: redis
    redis:
        host: localhost
        port: 6378
    cloud:
        gateway:
            httpclient:
                connect-timeout: 20
management:
    endpoint:
        health:
            cache:
                time-to-live: 30s
            show-details: always
    endpoints:
        web:
            base-path: /v1/actuator
            exposure:
                include: '*'

