logging:
    level:
        root: INFO
sample:
    internal-api: http://api-internal-sample:5001
server:
    port: 5000
spring:
    redis:
        host: redis-sample
        port: 6379
    security:
        oauth2:
            client:
                provider:
                    keycloak:
                        token-uri: http://keycloak-sample:6180/auth/realms/master/protocol/openid-connect/token
                        authorization-uri: http://keycloak-sample:6180/auth/realms/master/protocol/openid-connect/auth
                        userinfo-uri: http://keycloak-sample:6180/auth/realms/master/protocol/openid-connect/userinfo