#https://github.com/justb4/docker-jmeter
#docker-compose.yml (Base)
version: "3.7"
networks:
  sample:
    name: sample-network
    driver: bridge
services:
  jmeter-load-sample:
    container_name: jmeter-load-sample
    image: jmeter-sample
    networks:
      - sample
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: ["sh", "load_run.sh"]
  jmeter-page-sample:
    container_name: jmeter-page-sample
    image: jmeter-sample
    networks:
      - sample
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: ["sh", "page_run.sh"]
