# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3.7"
services:
  fe-dev:
    build:
      context: .
    container_name: fe-dev
    ports:
      - "3001:3000"
    networks:
      - sample
networks:
  sample:
    name: sample-network
    driver: bridge
