server:
  port: 8888
info:
  app:
    description: playground application
    name: Spring Backyard Cloud Config Application
  java-vendor: ${java.specification.vendor}
logging:
  level:
    root: DEBUG
spring:
  datasource:
    password: dev123
    url: jdbc:postgresql://localhost:5432/config?stringtype=unspecified
    username: dev
  flyway:
    locations: classpath:/db/migration/
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    config:
      vault:
        authentication: TOKEN
        token: sample
      server:
        monitor:
          github:
            enabled: true
        native:
          search-locations: classpath:/config
          order: 2
        git:
          uri: https://github.com/IT-Labs/backyard
          skipSslValidation: true
          searchPaths: cloud-config
          default-label: spring-cloud-config
#          force-pull: true
#          deleteUntrackedBranches: true
          order: 1
        vault:
          port: 8200
          host: localhost
          kvVersion: 1
          order: 1
        jdbc:
          sql: SELECT key, value FROM properties WHERE application=? AND profile=? AND label=?;
          order: 3
          default-label: label
  cache:
    type: redis
  redis:
    host: localhost
    port: 6378
  application:
    name: api-cloud-config-sample
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev123
    virtual-host: /
management:
  health:
    vault:
      enabled: false
  endpoint:
    health:
      cache:
        time-to-live: 30s
      show-details: always
  endpoints:
    web:
      base-path: /v1/actuator
      exposure:
        include: "*"
---
logging:
  level:
    root: DEBUG
server:
  port: 8888
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq-sample
  redis:
    host: redis-sample
    port: 6379
