server:
  port: 8888
info:
  app:
    description: playground application
    name: Spring Backyard Cloud Config Application
  java-vendor: ${java.specification.vendor}
logging:
  level:
    root: DEBUG
spring:
  cloud:
    bus:
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}
      enabled: true
      refresh:
        enabled: true
    config:
      #      enabled: true
      vault:
        authentication: TOKEN
        token: sample
      server:
        native:
          search-locations: classpath:/config
          order: 2
        git:
          uri: https://github.com/IT-Labs/backyard
          skipSslValidation: true
          searchPaths: cloud-config
          default-label: spring-cloud-config
          order: 1
        vault:
          port: 8200
          host: localhost
          kvVersion: 1
          order: 1
  cache:
    type: redis
  redis:
    host: localhost
    port: 6378
  application:
    name: api-cloud-config-sample
  rabbitmq:
    host: localhost
    port: 5672
    username: dev
    password: dev123
    virtual-host: /
management:
  health:
    vault:
      enabled: false
  endpoint:
    health:
      cache:
        time-to-live: 30s
      show-details: always
  endpoints:
    web:
      base-path: /v1/actuator
      exposure:
        include: "*"
---
logging:
  level:
    root: DEBUG
server:
  port: 8888
spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: rabbitmq-sample
  redis:
    host: redis-sample
    port: 6379
