#docker-compose.yml (Base)
version: "3.7"
services:
  api-dev:
    image: "openjdk:13.0.2-slim"
    container_name: api-dev
    volumes:
      - ./build/libs:/usr/src/myapp
    working_dir: /usr/src/myapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command:
      [
        "java",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/usr/src/myapp/service.jar",
      ]
    networks:
      - sample
    expose:
      - "5000"
    ports:
      - 5000:5000
    depends_on:
      - api-postgres
  api-postgres:
    image: postgres:12.2
    container_name: api-postgres
    environment:
      - "POSTGRES_PASSWORD=dev123"
      - "POSTGRES_USER=dev"
      - "POSTGRES_DB=sample"
    volumes:
      - api-postgres:/var/lib/postgresql/data:z
    ports:
      - "5444:5432"
    networks:
      - sample
networks:
  sample:
    name: sample-network
    driver: bridge
volumes:
  api-postgres:
    external: true
