#docker-compose.yml (Base)
version: '3.7'
services:
  tests:
    image: "openjdk:17-jdk-slim-buster"
    container_name: test-api
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command:  ./gradlew clean test jacocoTestReport