#docker-compose.yml (Base)
version: "3.7"
networks:
  sample:
    name: sample-network
    driver: bridge
services:
  api-internal-sample:
    image: "openjdk:11.0.9-slim"
    container_name: api-internal-sample
    volumes:
      - ./build/libs:/usr/src/myapp
    working_dir: /usr/src/myapp
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command:
      [
        "java",
        "-Djava.security.egd=file:/dev/./urandom",
        "-jar",
        "/usr/src/myapp/service.jar",
      ]
    networks:
      - sample
    expose:
      - "5001"
    ports:
      - 5001:5001
    depends_on:
      - flyway-sample
  flyway-sample:
    image: flyway/flyway:6.5.7-alpine
    container_name: flyway-sample
    command: -url=jdbc:postgresql://api-postgres/sample -schemas=public -user=dev -password=dev123 migrate
    volumes:
      - ./build/resources/main/db/migration:/flyway/sql
    networks:
      - sample
