#docker-compose.yml (Base)
version: '3.7'
services:
  build:
    image: "openjdk:15.0.2-slim"
    container_name: build-api
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp    
    command:  ./gradlew clean format build -x test